### ISSUE TITLE
jstree权限菜单显示问题

### ISSUE THREAD

**Issue by LXKing** [yoyocms/YoYoCms.AbpProjectTemplate#2]
PermissionTree.vue文件下
        watch: {
            'showList' (val) {
                if (val) {
                    console.log(1)
                    window.addEventListener('click', this.hideList)
                    this.init()
                } else window.removeEventListener('click', this.hideList)
            },
应改为
watch: {
            'showList' (val) {
                if (val) {
                    console.log(1)
                    window.addEventListener('click', this.showList)
                    this.init()
                } else window.removeEventListener('click', this.showList)
            },

**Comment by ltm0203** [comment]
欢迎提交PR
